// ============================================================
// lib/mockDatabase.ts — Complete Seed Data for All 5 Categories
// COE Portal: 5 Corporate Accounts + 5 Vendor Accounts (one per category)
// + All Category RFPs with Live Bids
// ============================================================

import { User, CorporateProfile, VendorProfile, RFP, Bid } from './types';
import { generatePreseededUsers, generatePreseededVendorProfiles } from '@/data/venues';

// ─── Seed Users — Login Credentials ────────────────────────────
// CORPORATE ACCOUNTS:
//   1. hr@nexus.com            → pass: test1234  → Sports + Food + Trips
//   2. admin.ops@apexfin.com   → pass: test1234  → Gifts + Dress
//   3. people@indigotec.com    → pass: test1234  → All categories (new entries)
// VENDOR ACCOUNTS:
//   4. sports@arenaturf.com    → pass: test1234  → Sports category
//   5. food@royalfeast.in      → pass: test1234  → Food category
//   6. trips@summitretreats.in → pass: test1234  → Trips category
//   7. gifts@luxehampers.com   → pass: test1234  → Gifts category
//   8. dress@threadsco.in      → pass: test1234  → Dress & Merchandise
// ADMIN:
//   9. admin@coe.com           → pass: test1234  → Super Admin
// PRE-SEEDED GURUGRAM VENUES (33 Accounts):
//   e.g. playall123@coe.com, whiskysamba123@coe.com, toybox123@coe.com → pass: gurgaon123

const BASE_SEED_USERS: User[] = [
  // ── Corporate Users ──
  {
    id: 'user_corp_01',
    email: 'hr@nexus.com',
    role: 'corporate',
    createdAt: '2026-07-20T10:00:00Z',
    isSuspended: false,
  },
  {
    id: 'user_corp_02',
    email: 'admin.ops@apexfin.com',
    role: 'corporate',
    createdAt: '2026-07-22T11:30:00Z',
    isSuspended: false,
  },
  {
    id: 'user_corp_03',
    email: 'people@indigotec.com',
    role: 'corporate',
    createdAt: '2026-07-25T09:00:00Z',
    isSuspended: false,
  },

  // ── Vendor Users ──
  {
    id: 'user_vendor_sports',
    email: 'sports@arenaturf.com',
    role: 'vendor',
    createdAt: '2026-07-21T09:00:00Z',
    isSuspended: false,
  },
  {
    id: 'user_vendor_food',
    email: 'food@royalfeast.in',
    role: 'vendor',
    createdAt: '2026-07-21T10:30:00Z',
    isSuspended: false,
  },
  {
    id: 'user_vendor_trips',
    email: 'trips@summitretreats.in',
    role: 'vendor',
    createdAt: '2026-07-22T14:00:00Z',
    isSuspended: false,
  },
  {
    id: 'user_vendor_gifts',
    email: 'gifts@luxehampers.com',
    role: 'vendor',
    createdAt: '2026-07-23T11:00:00Z',
    isSuspended: false,
  },
  {
    id: 'user_vendor_dress',
    email: 'dress@threadsco.in',
    role: 'vendor',
    createdAt: '2026-07-24T15:00:00Z',
    isSuspended: false,
  },

  // ── Admin ──
  {
    id: 'user_admin_01',
    email: 'admin@coe.com',
    role: 'admin',
    createdAt: '2026-07-01T08:00:00Z',
    isSuspended: false,
  },

  // ── Extra vendor users for multiple bids ──
  {
    id: 'user_vendor_sports_02',
    email: 'sports2@proleagues.in',
    role: 'vendor',
    createdAt: '2026-07-25T09:00:00Z',
    isSuspended: false,
  },
  {
    id: 'user_vendor_food_02',
    email: 'food2@cyberhubgourmet.com',
    role: 'vendor',
    createdAt: '2026-07-25T10:00:00Z',
    isSuspended: false,
  },
  {
    id: 'user_vendor_trips_02',
    email: 'trips2@wandercraft.in',
    role: 'vendor',
    createdAt: '2026-07-25T11:00:00Z',
    isSuspended: false,
  },
  {
    id: 'user_vendor_gifts_02',
    email: 'gifts2@arcadeawards.com',
    role: 'vendor',
    createdAt: '2026-07-25T12:00:00Z',
    isSuspended: false,
  },
  {
    id: 'user_vendor_dress_02',
    email: 'dress2@brandwear.in',
    role: 'vendor',
    createdAt: '2026-07-25T13:00:00Z',
    isSuspended: false,
  },
];

export const SEED_USERS: User[] = [
  ...BASE_SEED_USERS,
  ...generatePreseededUsers(),
];

// ─── Corporate Profiles ────────────────────────────────────────
export const SEED_CORPORATE_PROFILES: CorporateProfile[] = [
  // ── Corp 01: Nexus Technologies — hr@nexus.com ──
  {
    id: 'corp_prof_01',
    userId: 'user_corp_01',
    name: 'Sarah Sharma',
    mobile: '+91 98112 34567',
    email: 'hr@nexus.com',
    officeCompanyName: 'Nexus Technologies India',
    officeAddress: 'Building 10B, 8th Floor, DLF Cyber City, Phase II, Gurugram 122002',
    city: 'Gurugram',
    position: 'VP of Human Resources & People Ops',
    department: 'People Operations',
    cinNumber: 'U72900HR2018PTC075432',
    teamSize: '500-2000 Employees',
    annualProcurementBudget: '₹2 Cr - ₹5 Cr',
    isCompleted: true,
    status: 'approved',
    submittedAt: '2026-07-20T10:30:00Z',
    verifiedAt: '2026-07-20T14:00:00Z',
  },
  // ── Corp 02: Apex Financial Services — admin.ops@apexfin.com ──
  {
    id: 'corp_prof_02',
    userId: 'user_corp_02',
    name: 'Vikas Mehta',
    mobile: '+91 98201 98765',
    email: 'admin.ops@apexfin.com',
    officeCompanyName: 'Apex Financial Services',
    officeAddress: 'Tower 4, Horizon Center, Golf Course Road, Gurugram 122002',
    city: 'Gurugram',
    position: 'Head of Employee Engagement',
    department: 'Corporate Workplace Operations',
    cinNumber: 'U65999HR2020PTC088910',
    teamSize: '200-500 Employees',
    annualProcurementBudget: '₹50 Lakh - ₹1 Cr',
    isCompleted: true,
    status: 'approved',
    submittedAt: '2026-07-22T11:00:00Z',
    verifiedAt: '2026-07-22T15:00:00Z',
  },
  // ── Corp 03: Indigo Technologies — people@indigotec.com ──
  {
    id: 'corp_prof_03',
    userId: 'user_corp_03',
    name: 'Meera Pillai',
    mobile: '+91 99100 55432',
    email: 'people@indigotec.com',
    officeCompanyName: 'Indigo Technologies Pvt Ltd',
    officeAddress: 'Unit 602, Emaar Business Park, MG Road, Gurugram 122002',
    city: 'Gurugram',
    position: 'Senior Manager – People & Culture',
    department: 'Human Resources',
    cinNumber: 'U74999HR2019PTC081234',
    teamSize: '200-500 Employees',
    annualProcurementBudget: '₹1 Cr - ₹3 Cr',
    isCompleted: true,
    status: 'approved',
    submittedAt: '2026-07-25T09:30:00Z',
    verifiedAt: '2026-07-25T13:00:00Z',
  },
  // ── Corp 04: Pending Account (for admin testing) ──
  {
    id: 'corp_prof_04',
    userId: 'user_corp_pending',
    name: 'Rohit Singhania',
    mobile: '+91 98100 12345',
    email: 'rohit@newstartup.io',
    officeCompanyName: 'Quantum Fintech Solutions',
    officeAddress: 'Block B3, Sohna Road, Gurugram 122018',
    city: 'Gurugram',
    position: 'Founding Team – Operations',
    department: 'Administration',
    cinNumber: 'U74999HR2024PTC099876',
    teamSize: '50-200 Employees',
    annualProcurementBudget: '₹10 Lakh - ₹50 Lakh',
    isCompleted: true,
    status: 'pending',
    submittedAt: '2026-08-16T09:40:00Z',
  },
];

// ─── Vendor Profiles ────────────────────────────────────────────
const BASE_VENDOR_PROFILES: VendorProfile[] = [
  // ── SPORTS: Arena Turf Sports Management — sports@arenaturf.com ──
  {
    id: 'vendor_sports_01',
    userId: 'user_vendor_sports',
    category: 'sports',
    vendorName: 'Vikram Singh',
    companyName: 'Arena Turf Sports Management',
    mobile: '+91 99100 88776',
    companyMobile: '+91 0124 3322110',
    address: 'Sector 54, Golf Course Road, Gurugram',
    city: 'Gurugram',
    distanceKm: 4.5,
    entityType: 'Pvt Ltd',
    panNumber: 'AAACA1234V',
    gstNumber: '07AAACA1234V1Z3',
    gstVerified: true,
    portfolioSummary: 'Turnkey corporate sports leagues: box cricket, turf football, badminton, and mini-olympics. Certified referees, live scoring apps, custom trophies & team jerseys.',
    pastClients: ['Uber India', 'PwC', 'KPMG', 'Paytm', 'Swiggy'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-21T09:30:00Z',
    verifiedAt: '2026-07-21T14:00:00Z',
    place_id: 'ChIJF33Q-tUZDTkReb1mY8jWl1w',
    placeName: 'Arena Turf Sports Complex',
    formatted_address: 'Sector 54, Golf Course Road, Gurugram, Haryana 122011',
    lat: 28.4352,
    lng: 77.1086,
    rating: 4.8,
    user_ratings_total: 142,
  },
  // Extra sports vendor for bid variety
  {
    id: 'vendor_sports_02',
    userId: 'user_vendor_sports_02',
    category: 'sports',
    vendorName: 'Manish Rawat',
    companyName: 'ProLeagues Corporate Tournaments',
    mobile: '+91 98188 44332',
    companyMobile: '+91 0124 2233445',
    address: 'Sector 29, Leisure Valley Park, Gurugram',
    city: 'Gurugram',
    distanceKm: 3.2,
    entityType: 'LLP',
    panNumber: 'AABCM5678P',
    gstNumber: '07AABCM5678P1Z9',
    gstVerified: true,
    portfolioSummary: 'Full tournament management with YouTube live broadcast, multi-camera HD coverage, DJ & commentary, player kits, and on-site physiotherapist.',
    pastClients: ['Tata 1mg', 'MakeMyTrip', 'OYO', 'PolicyBazaar', 'Rapido'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-25T09:30:00Z',
    verifiedAt: '2026-07-25T14:00:00Z',
    place_id: 'ChIJF33Q-tUZDTkReb1mY8jWl1w',
    placeName: 'ProLeagues Sports Arena',
    formatted_address: 'Sector 29, Leisure Valley Park, Gurugram, Haryana 122001',
    lat: 28.4682,
    lng: 77.0634,
    rating: 4.7,
    user_ratings_total: 98,
  },

  // ── FOOD: Royal Feast Catering — food@royalfeast.in ──
  {
    id: 'vendor_food_01',
    userId: 'user_vendor_food',
    category: 'food',
    vendorName: 'Rajat Verma',
    companyName: 'Royal Feast Catering & Mixology',
    mobile: '+91 98711 22334',
    companyMobile: '+91 0124 4567890',
    address: 'Plaza 3, DLF Phase 1, Gurugram',
    city: 'Gurugram',
    distanceKm: 2.8,
    entityType: 'Pvt Ltd',
    panNumber: 'AAACR1234F',
    gstNumber: '07AAACR1234F1Z5',
    gstVerified: true,
    portfolioSummary: 'Five-star catering: live gourmet counters, cocktail lounges, executive gala dinners, multi-cuisine corporate spreads, and bespoke menu engineering for 50–2000 pax.',
    pastClients: ['Google India', 'Microsoft', 'Zomato', 'Deloitte', 'Goldman Sachs'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-21T10:00:00Z',
    verifiedAt: '2026-07-21T14:00:00Z',
    place_id: 'ChIJ8-U9tI0ZDTkR70-H1M8vDqk',
    placeName: 'Royal Feast Banquet & Culinary Hub',
    formatted_address: 'Plaza 3, DLF Phase 1, Gurugram, Haryana 122002',
    lat: 28.4827,
    lng: 77.0917,
    rating: 4.9,
    user_ratings_total: 218,
  },
  // Extra food vendor
  {
    id: 'vendor_food_02',
    userId: 'user_vendor_food_02',
    category: 'food',
    vendorName: 'Amit Soni',
    companyName: 'CyberHub Gourmet Hospitality',
    mobile: '+91 98110 55443',
    companyMobile: '+91 0124 4998877',
    address: 'DLF Cyber Hub Promenade, Gurugram',
    city: 'Gurugram',
    distanceKm: 1.1,
    entityType: 'Pvt Ltd',
    panNumber: 'AAACS5678G',
    gstNumber: '07AAACS5678G1Z2',
    gstVerified: true,
    portfolioSummary: 'Located inside DLF Cyber Hub — zero logistics delay. Premium culinary brigade, pre-event tasting session, imported glassware, and full banquet management.',
    pastClients: ['American Express', 'KPMG', 'Accenture', 'PwC', 'EY India'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-25T10:00:00Z',
    verifiedAt: '2026-07-25T14:00:00Z',
    place_id: 'ChIJ8-U9tI0ZDTkR70-H1M8vDqk',
    placeName: 'CyberHub Gourmet Kitchen',
    formatted_address: 'DLF Cyber Hub Promenade, Gurugram, Haryana 122002',
    lat: 28.4952,
    lng: 77.0877,
    rating: 4.8,
    user_ratings_total: 165,
  },

  // ── TRIPS: Summit Corporate Retreats — trips@summitretreats.in ──
  {
    id: 'vendor_trips_01',
    userId: 'user_vendor_trips',
    category: 'trips',
    vendorName: 'Priya Nambiar',
    companyName: 'Summit Corporate Retreats',
    mobile: '+91 98450 11223',
    companyMobile: '+91 080 23456789',
    address: 'MG Road & DLF Cyber City, Gurugram',
    city: 'Gurugram',
    distanceKm: 6.2,
    entityType: 'Pvt Ltd',
    panNumber: 'AAACN1234T',
    gstNumber: '29AAACN1234T1Z1',
    gstVerified: true,
    portfolioSummary: 'End-to-end executive offsite planning: hill stations, beach resorts & heritage destinations. Conference logistics, team-building adventure, gala banquet & chartered transport.',
    pastClients: ['Flipkart', 'Swiggy', 'Infosys', 'Cred', 'Razorpay'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-22T14:00:00Z',
    verifiedAt: '2026-07-22T18:00:00Z',
    place_id: 'ChIJS3-z0jYZDTkRG-Qz-fK1j1U',
    placeName: 'Summit Corporate Travel Lounge',
    formatted_address: 'DLF Cyber City & MG Road, Gurugram, Haryana 122002',
    lat: 28.4912,
    lng: 77.0864,
    rating: 4.7,
    user_ratings_total: 89,
  },
  // Extra trips vendor
  {
    id: 'vendor_trips_02',
    userId: 'user_vendor_trips_02',
    category: 'trips',
    vendorName: 'Arjun Bose',
    companyName: 'WanderCraft Experiential Travel',
    mobile: '+91 98990 33445',
    companyMobile: '+91 011 44556677',
    address: 'Connaught Place & DLF Phase 2, Gurugram',
    city: 'Gurugram',
    distanceKm: 28.0,
    entityType: 'LLP',
    panNumber: 'AABCW9012T',
    gstNumber: '07AABCW9012T1Z4',
    gstVerified: true,
    portfolioSummary: 'Bespoke corporate travel experiences: Rajasthan heritage trails, Kerala backwater offsites, Goa beach workations, and international executive retreats.',
    pastClients: ['Amazon India', 'Samsung India', 'Hyundai', 'Bajaj Finserv', 'Nykaa'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-25T11:00:00Z',
    verifiedAt: '2026-07-25T15:00:00Z',
    place_id: 'ChIJS3-z0jYZDTkRG-Qz-fK1j1U',
    placeName: 'WanderCraft Travel Desk',
    formatted_address: 'DLF Phase 2, Gurugram, Haryana 122002',
    lat: 28.4876,
    lng: 77.0845,
    rating: 4.6,
    user_ratings_total: 72,
  },

  // ── GIFTS: Luxe Hampers & Bespoke Awards — gifts@luxehampers.com ──
  {
    id: 'vendor_gifts_01',
    userId: 'user_vendor_gifts',
    category: 'gifts',
    vendorName: 'Ananya Roy',
    companyName: 'Luxe Hampers & Bespoke Awards',
    mobile: '+91 98200 44556',
    companyMobile: '+91 022 66778899',
    address: 'Udyog Vihar Phase 4, Gurugram',
    city: 'Gurugram',
    distanceKm: 3.1,
    entityType: 'Pvt Ltd',
    panNumber: 'AAACAR1234G',
    gstNumber: '07AAACAR1234G1Z4',
    gstVerified: true,
    portfolioSummary: 'Curated corporate gifting: Diwali hampers, new joiner welcome kits, recognition crystal trophies, customized leather journals, and branded lifestyle accessories.',
    pastClients: ['American Express', 'Bain & Co.', 'McKinsey', 'JP Morgan', 'Citi India'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-23T11:00:00Z',
    verifiedAt: '2026-07-23T15:00:00Z',
    place_id: 'ChIJp7tY5N8ZDTkRkJ3-e8-1z1Y',
    placeName: 'Luxe Corporate Gifting Studio',
    formatted_address: 'Udyog Vihar Phase 4, Gurugram, Haryana 122015',
    lat: 28.5021,
    lng: 77.0812,
    rating: 4.9,
    user_ratings_total: 176,
  },
  // Extra gifts vendor
  {
    id: 'vendor_gifts_02',
    userId: 'user_vendor_gifts_02',
    category: 'gifts',
    vendorName: 'Kanchan Mehta',
    companyName: 'Arcade Awards & Gifting Studio',
    mobile: '+91 99887 33221',
    companyMobile: '+91 0124 9988776',
    address: 'Sector 44, Gurugram',
    city: 'Gurugram',
    distanceKm: 4.7,
    entityType: 'Proprietorship',
    panNumber: 'AABCM1122G',
    gstNumber: '07AABCM1122G1Z7',
    gstVerified: true,
    portfolioSummary: 'Eco-friendly gifting solutions: sustainable bamboo kits, organic Diwali hampers, 3D-engraved crystal awards, and fully customizable employee recognition programs.',
    pastClients: ['HCL Technologies', 'Wipro', 'Infosys BPM', 'Tech Mahindra'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-25T12:00:00Z',
    verifiedAt: '2026-07-25T16:00:00Z',
    place_id: 'ChIJp7tY5N8ZDTkRkJ3-e8-1z1Y',
    placeName: 'Arcade Awards & Trophy House',
    formatted_address: 'Sector 44, Institutional Area, Gurugram, Haryana 122003',
    lat: 28.4512,
    lng: 77.0723,
    rating: 4.8,
    user_ratings_total: 114,
  },

  // ── DRESS: Threads & Co. Corporate Apparel — dress@threadsco.in ──
  {
    id: 'vendor_dress_01',
    userId: 'user_vendor_dress',
    category: 'dress',
    vendorName: 'Karan Kapoor',
    companyName: 'Threads & Co. Corporate Apparel',
    mobile: '+91 98101 77889',
    companyMobile: '+91 011 29876543',
    address: 'DLF Cyber City & Udyog Vihar, Gurugram',
    city: 'Gurugram',
    distanceKm: 2.5,
    entityType: 'Pvt Ltd',
    panNumber: 'AAACK1234D',
    gstNumber: '07AAACK1234D1Z7',
    gstVerified: true,
    portfolioSummary: 'Bespoke corporate apparel: tech hoodies, embroidered polo shirts, winter jackets, branded backpacks, and event-specific custom merchandise with same-city delivery.',
    pastClients: ['Uber India', 'Razorpay', 'Cult.fit', 'Urban Company', 'Flipkart'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-24T10:00:00Z',
    verifiedAt: '2026-07-24T14:00:00Z',
    place_id: 'ChIJh7-z890ZDTkRsM-1x2y-z1Z',
    placeName: 'Threads & Co. Merch Studio',
    formatted_address: 'DLF Cyber City Promenade, Gurugram, Haryana 122002',
    lat: 28.4947,
    lng: 77.0886,
    rating: 4.8,
    user_ratings_total: 134,
  },
  // Extra dress vendor
  {
    id: 'vendor_dress_02',
    userId: 'user_vendor_dress_02',
    category: 'dress',
    vendorName: 'Sonal Jain',
    companyName: 'BrandWear Merchandise Studio',
    mobile: '+91 98990 12233',
    companyMobile: '+91 0124 6655443',
    address: 'Sector 18 & DLF Phase 3, Gurugram',
    city: 'Gurugram',
    distanceKm: 4.2,
    entityType: 'LLP',
    panNumber: 'AABCS3456D',
    gstNumber: '06AABCS3456D1Z2',
    gstVerified: true,
    portfolioSummary: 'High-volume corporate merchandise: 100–10,000 units. Premium sublimation printing, embroidery, offset-printed merchandise boxes, and white-label brand packaging.',
    pastClients: ['Samsung India', 'LG Electronics', 'Hero MotoCorp', 'Maruti Suzuki'],
    status: 'approved',
    isCompleted: true,
    submittedAt: '2026-07-25T13:00:00Z',
    verifiedAt: '2026-07-25T17:00:00Z',
    place_id: 'ChIJh7-z890ZDTkRsM-1x2y-z1Z',
    placeName: 'BrandWear Studio Hub',
    formatted_address: 'Sector 18, Udyog Vihar, Gurugram, Haryana 122008',
    lat: 28.4891,
    lng: 77.0754,
    rating: 4.7,
    user_ratings_total: 86,
  },

  // ── Pending vendor (for admin testing) ──
  {
    id: 'vendor_pending_01',
    userId: 'user_vendor_pending',
    category: 'food',
    vendorName: 'Roshni Kapoor',
    companyName: 'Urban Eats Corporate Kitchen',
    mobile: '+91 99881 22334',
    companyMobile: '+91 0124 1122334',
    address: 'Vatika Business Park, Sohna Road, Gurugram',
    city: 'Gurugram',
    distanceKm: 7.3,
    entityType: 'Proprietorship',
    panNumber: 'AABCR7890F',
    gstNumber: '07AABCR7890F1Z6',
    gstVerified: false,
    portfolioSummary: 'Healthy corporate meals: daily tiffin services, weekly lunch buffets, and customized diet menus for wellness-focused corporate teams.',
    pastClients: ['Local Startups', 'Co-working Spaces'],
    status: 'pending',
    isCompleted: true,
    submittedAt: '2026-08-17T10:00:00Z',
  },
];

export const SEED_VENDOR_PROFILES: VendorProfile[] = [
  ...BASE_VENDOR_PROFILES,
  ...generatePreseededVendorProfiles(),
];

// ─── Seed RFPs — One per category per corporate ────────────────
export const SEED_RFPS: RFP[] = [
  // ═══ NEXUS TECHNOLOGIES (hr@nexus.com) ═══

  // RFP-01: Food — Annual Founders Gala
  {
    id: 'rfp_nexus_food',
    corporateId: 'corp_prof_01',
    corporateUserId: 'user_corp_01',
    companyName: 'Nexus Technologies India',
    category: 'food',
    categoryDetails: {
      mealType: 'Dinner Gala & Cocktail Networking',
      beverage: 'Alcoholic (Craft Cocktails & Wine)',
      menuPreference: 'Multi-Cuisine Buffet',
      cuisine: 'Pan-Asian & Continental Gourmet',
      entertainment: ['Live Acoustic Trio', 'Bespoke Bar Counter', 'Photo Booth'],
    },
    universal: {
      startDate: '2026-09-18',
      endDate: '2026-09-18',
      timeSlot: 'Evening Gala (7:00 PM - Midnight)',
      timeFlexibility: 'Flexible (±1 Hour)',
      urgency: 'Planned Quarter',
      persons: 250,
      budgetPerPerson: 3200,
      notes: 'Annual Founders Day celebration. Premium multi-cuisine buffet, craft mixology, live sushi & teppanyaki counters, executive allergen management required.',
      officeAddress: 'Building 10B, DLF Cyber City, Gurugram',
    },
    totalBudget: 800000,
    submittedAt: '2026-08-10T14:30:00Z',
    status: 'bid-received',
  },

  // RFP-02: Sports — Inter-Department Cricket League
  {
    id: 'rfp_nexus_sports',
    corporateId: 'corp_prof_01',
    corporateUserId: 'user_corp_01',
    companyName: 'Nexus Technologies India',
    category: 'sports',
    categoryDetails: {
      type: 'Box Cricket Premier League & Turf Football',
      extras: ['BCCI-Certified Umpires', 'HD Drone Coverage', 'Custom Team Jerseys', 'Crystal Trophies'],
    },
    universal: {
      startDate: '2026-09-26',
      endDate: '2026-09-27',
      timeSlot: 'Full Day Weekend Tournament (8:00 AM - 6:00 PM)',
      timeFlexibility: 'Strict Schedule',
      urgency: 'Planned Quarter',
      persons: 120,
      budgetPerPerson: 2500,
      notes: 'Inter-department 8-team box cricket + 4-team football league. Full turf booking, hydration stations, paramedic on-site, live app scoring system.',
      officeAddress: 'Building 10B, DLF Cyber City, Gurugram',
    },
    totalBudget: 300000,
    submittedAt: '2026-08-12T11:00:00Z',
    status: 'bid-received',
  },

  // RFP-03: Trips — Leadership Offsite Rishikesh
  {
    id: 'rfp_nexus_trips',
    corporateId: 'corp_prof_01',
    corporateUserId: 'user_corp_01',
    companyName: 'Nexus Technologies India',
    category: 'trips',
    categoryDetails: {
      destinationType: 'Hill Station Workation & Leadership Offsite',
      itineraryStyle: 'Luxury Resort & Adventure Team Building',
      transport: ['Chartered Volvo AC Coaches', 'Airport Pickup & Drop'],
      accommodation: '5-Star Resort (Twin Sharing)',
    },
    universal: {
      startDate: '2026-10-08',
      endDate: '2026-10-11',
      timeSlot: '3 Nights / 4 Days Executive Offsite',
      timeFlexibility: 'Flexible (±2 Days)',
      urgency: 'Planned Quarter',
      persons: 80,
      budgetPerPerson: 18000,
      notes: 'Leadership team annual offsite. Conference hall with AV, team adventure activities (rafting, zip-line), gala banquet on final night, all F&B included.',
      officeAddress: 'Building 10B, DLF Cyber City, Gurugram',
    },
    totalBudget: 1440000,
    submittedAt: '2026-08-14T09:15:00Z',
    status: 'bid-received',
  },

  // ═══ APEX FINANCIAL SERVICES (admin.ops@apexfin.com) ═══

  // RFP-04: Gifts — Diwali Hampers for 300 Employees
  {
    id: 'rfp_apex_gifts',
    corporateId: 'corp_prof_02',
    corporateUserId: 'user_corp_02',
    companyName: 'Apex Financial Services',
    category: 'gifts',
    categoryDetails: {
      purpose: 'Diwali Festival Gifting & Employee Appreciation',
      productTypes: ['Premium Dry Fruit Hampers', 'Branded Leather Diary & Pen Set', 'Artisan Mithai Box', 'Customized Tote Bags'],
      customLogo: true,
    },
    universal: {
      startDate: '2026-10-15',
      endDate: '2026-10-18',
      timeSlot: 'Delivery 3 days before Diwali',
      timeFlexibility: 'Strict Schedule',
      urgency: 'Upcoming Month',
      persons: 300,
      budgetPerPerson: 1800,
      notes: 'Diwali hampers for all 300 employees at Horizon Center office. Company logo embossing on packaging, GST invoice required, delivered to office reception.',
      officeAddress: 'Tower 4, Horizon Center, Golf Course Road, Gurugram',
    },
    totalBudget: 540000,
    submittedAt: '2026-08-15T12:00:00Z',
    status: 'bid-received',
  },

  // RFP-05: Dress — Year-End Branded Merchandise
  {
    id: 'rfp_apex_dress',
    corporateId: 'corp_prof_02',
    corporateUserId: 'user_corp_02',
    companyName: 'Apex Financial Services',
    category: 'dress',
    categoryDetails: {
      apparelType: ['Corporate Polo T-Shirts', 'Tech Fleece Hoodies', 'Branded Backpacks'],
      addOns: ['Embossed Company Logo', 'Individual Name Printing', 'Premium Packaging Boxes'],
      material: 'Premium Cotton-Polyester Blend (240 GSM)',
    },
    universal: {
      startDate: '2026-11-01',
      endDate: '2026-11-05',
      timeSlot: 'Year-End Merchandise Delivery',
      timeFlexibility: 'Flexible (±3 Days)',
      urgency: 'Planned Quarter',
      persons: 250,
      budgetPerPerson: 2400,
      notes: 'Year-end branded merchandise for 250 employees. Mix of polo shirts (S to 3XL), hoodies, and premium backpacks. All items with company logo embroidery.',
      officeAddress: 'Tower 4, Horizon Center, Golf Course Road, Gurugram',
    },
    totalBudget: 600000,
    submittedAt: '2026-08-16T10:00:00Z',
    status: 'bid-received',
  },

  // ═══ INDIGO TECHNOLOGIES (people@indigotec.com) ═══

  // RFP-06: Sports — Badminton & Table Tennis Day
  {
    id: 'rfp_indigo_sports',
    corporateId: 'corp_prof_03',
    corporateUserId: 'user_corp_03',
    companyName: 'Indigo Technologies Pvt Ltd',
    category: 'sports',
    categoryDetails: {
      type: 'Badminton Tournament & Table Tennis Championship',
      extras: ['Professional Referees', 'Badminton Racket Sets', 'Medals & Certificates', 'Health Snack Station'],
    },
    universal: {
      startDate: '2026-09-20',
      endDate: '2026-09-20',
      timeSlot: 'Morning & Afternoon (9:00 AM - 5:00 PM)',
      timeFlexibility: 'Flexible (±1 Day)',
      urgency: 'Upcoming Month',
      persons: 60,
      budgetPerPerson: 1500,
      notes: 'Company sports day: single-day badminton tournament (32-player draw) + TT championship (16-player). Court rental, rackets, shuttles, referees, and medals needed.',
      officeAddress: 'Unit 602, Emaar Business Park, MG Road, Gurugram',
    },
    totalBudget: 90000,
    submittedAt: '2026-08-13T15:00:00Z',
    status: 'bid-received',
  },

  // RFP-07: Food — Monthly Team Lunch
  {
    id: 'rfp_indigo_food',
    corporateId: 'corp_prof_03',
    corporateUserId: 'user_corp_03',
    companyName: 'Indigo Technologies Pvt Ltd',
    category: 'food',
    categoryDetails: {
      mealType: 'Working Lunch & Networking Buffet',
      beverage: 'Non-Alcoholic (Mocktails, Fresh Juices & Cold Brew)',
      menuPreference: 'Regional Indian Cuisine',
      cuisine: 'North Indian & South Indian Specialties',
      entertainment: ['Background Music Playlist'],
    },
    universal: {
      startDate: '2026-09-05',
      endDate: '2026-09-05',
      timeSlot: 'Working Lunch (12:30 PM - 3:00 PM)',
      timeFlexibility: 'Flexible (±1 Hour)',
      urgency: 'Upcoming Month',
      persons: 80,
      budgetPerPerson: 1200,
      notes: 'Monthly all-hands team lunch. Vegetarian-heavy menu with Rajasthani thali & South Indian live dosa counter. Jain options required for 12 employees.',
      officeAddress: 'Unit 602, Emaar Business Park, MG Road, Gurugram',
    },
    totalBudget: 96000,
    submittedAt: '2026-08-11T13:00:00Z',
    status: 'bid-received',
  },

  // RFP-08: Trips — Goa Team Offsite
  {
    id: 'rfp_indigo_trips',
    corporateId: 'corp_prof_03',
    corporateUserId: 'user_corp_03',
    companyName: 'Indigo Technologies Pvt Ltd',
    category: 'trips',
    categoryDetails: {
      destinationType: 'Beach Resort Workation & Team Bonding',
      itineraryStyle: 'Mid-Range Resort + Adventure Activities',
      transport: ['IndiGo/SpiceJet Economy Flights', 'AC Mini-Bus Airport Transfer'],
      accommodation: '4-Star Beach Resort (Triple Sharing)',
    },
    universal: {
      startDate: '2026-11-14',
      endDate: '2026-11-17',
      timeSlot: '3 Nights / 4 Days Goa Offsite',
      timeFlexibility: 'Flexible (±1 Week)',
      urgency: 'Planned Quarter',
      persons: 45,
      budgetPerPerson: 22000,
      notes: 'Year-end team offsite to Goa. Flight + 4-star beach resort + water sports (jet ski, parasailing) + beach bonfire dinner + half-day North Goa sightseeing.',
      officeAddress: 'Unit 602, Emaar Business Park, MG Road, Gurugram',
    },
    totalBudget: 990000,
    submittedAt: '2026-08-15T11:00:00Z',
    status: 'open',
  },

  // RFP-09: Gifts — New Joiner Welcome Kits
  {
    id: 'rfp_indigo_gifts',
    corporateId: 'corp_prof_03',
    corporateUserId: 'user_corp_03',
    companyName: 'Indigo Technologies Pvt Ltd',
    category: 'gifts',
    categoryDetails: {
      purpose: 'New Joiner Welcome Kit & Onboarding Experience',
      productTypes: ['Premium Laptop Sleeve', 'Branded Notebook & Pen', 'Company Hoodie', 'Succulent Plant Kit', 'Welcome Card'],
      customLogo: true,
    },
    universal: {
      startDate: '2026-09-01',
      endDate: '2026-09-30',
      timeSlot: 'Monthly Recurring Order (30 kits/month)',
      timeFlexibility: 'Flexible (Monthly delivery)',
      urgency: 'Immediate (Next 7-10 Days)',
      persons: 30,
      budgetPerPerson: 2500,
      notes: 'Monthly welcome kit subscription for 30 new joiners. Each kit in a branded box with tissue wrap. Delivery to office on 1st of each month.',
      officeAddress: 'Unit 602, Emaar Business Park, MG Road, Gurugram',
    },
    totalBudget: 75000,
    submittedAt: '2026-08-12T14:00:00Z',
    status: 'bid-received',
  },

  // RFP-10: Dress — Engineer-Day Branded T-Shirts
  {
    id: 'rfp_indigo_dress',
    corporateId: 'corp_prof_03',
    corporateUserId: 'user_corp_03',
    companyName: 'Indigo Technologies Pvt Ltd',
    category: 'dress',
    categoryDetails: {
      apparelType: ['Graphic Print Round-Neck T-Shirts', 'Caps/Snapbacks'],
      addOns: ['Custom Artwork Design', 'Individual Size Packaging'],
      material: 'Supima Cotton (180 GSM) - Premium Soft',
    },
    universal: {
      startDate: '2026-09-15',
      endDate: '2026-09-15',
      timeSlot: 'Engineers Day (Sep 15) Delivery',
      timeFlexibility: 'Strict Schedule',
      urgency: 'Upcoming Month',
      persons: 90,
      budgetPerPerson: 800,
      notes: 'Engineers Day T-shirts for the entire engineering team. Unique graphic design with tech/code theme. Caps optional. Sizes: XS to 3XL.',
      officeAddress: 'Unit 602, Emaar Business Park, MG Road, Gurugram',
    },
    totalBudget: 72000,
    submittedAt: '2026-08-14T16:00:00Z',
    status: 'bid-received',
  },
];

// ─── Seed Bids — All Categories ────────────────────────────────
export const SEED_BIDS: Bid[] = [
  // ═══ FOOD BIDS ═══

  // Bids for rfp_nexus_food (Nexus Founders Gala)
  {
    id: 'bid_nexus_food_01',
    rfpId: 'rfp_nexus_food',
    vendorId: 'vendor_food_01',
    vendorUserId: 'user_vendor_food',
    vendorName: 'Rajat Verma',
    vendorCompany: 'Royal Feast Catering & Mixology',
    category: 'food',
    totalPrice: 750000,
    distanceKm: 2.8,
    matchPercentage: 96,
    lineItems: [
      { description: 'Live Gourmet Stations (Sushi, Robata & Pasta) — 250 pax', amount: 480000 },
      { description: 'Premium Mixology Bar Setup & 4 Certified Bartenders', amount: 160000 },
      { description: 'Decor, Ambient Lighting & Service Staff (30 Stewards)', amount: 110000 },
    ],
    proposal: 'We have executed 50+ corporate galas in DLF Cyber City. Guaranteed top-tier hygiene, five-star executive service, and custom craft mixology menus tailored for Nexus Tech.',
    submittedAt: '2026-08-11T16:20:00Z',
    status: 'pending',
    rating: 4.9,
    user_ratings_total: 218,
    locality: 'Plaza 3, DLF Phase 1, Gurugram',
    timings: '12:00 PM - 12:00 AM',
    amenities: ['Artisanal Mixology', 'Pan-Asian Live Counters', 'Five-Star Stewards', 'Executive Dietary Care'],
  },
  {
    id: 'bid_nexus_food_whiskysamba',
    rfpId: 'rfp_nexus_food',
    vendorId: 'vp_venue_whiskysamba',
    vendorUserId: 'user_venue_whiskysamba',
    vendorName: 'Whisky Samba Executive Team',
    vendorCompany: 'Whisky Samba (One Horizon Center)',
    category: 'food',
    totalPrice: 800000,
    distanceKm: 2.8,
    matchPercentage: 99,
    lineItems: [
      { description: 'Robata Grill, Haute Pan-Asian Live Stations & C-Suite Dining (250 pax)', amount: 520000 },
      { description: '50-Foot Long Island Bar Setup & Single Malt Vault Curations', amount: 180000 },
      { description: 'Private Sommelier, Mixologists & Dedicated VIP Service Stewards', amount: 100000 },
    ],
    proposal: 'Benchmark luxury dining from Two Horizon Center. Signature robata grills, award-winning mixology, and white-glove executive hospitality tailored for Nexus Technologies.',
    submittedAt: '2026-08-11T17:15:00Z',
    status: 'pending',
    rating: 4.3,
    user_ratings_total: 3420,
    locality: 'Two Horizon Center, Golf Course Road',
    timings: '12:00 PM - 2:00 AM',
    amenities: ['50-Foot Bar', 'Single Malt Vault', 'Robata Grill', 'Private Dining Room'],
  },
  {
    id: 'bid_nexus_food_manhattan',
    rfpId: 'rfp_nexus_food',
    vendorId: 'vp_venue_manhattanbar',
    vendorUserId: 'user_venue_manhattanbar',
    vendorName: 'Manhattan Hospitality Desk',
    vendorCompany: 'Manhattan Bar & Brewery',
    category: 'food',
    totalPrice: 690000,
    distanceKm: 2.4,
    matchPercentage: 97,
    lineItems: [
      { description: 'Fresh In-House German Craft Beer Taps & Continental Buffet (250 pax)', amount: 440000 },
      { description: 'Cocktail Bar Lounge, Live DJ Stage & Interactive Sound/Lights', amount: 140000 },
      { description: 'Event Coordination, Cutlery, Live Pizza Oven & Stewards', amount: 110000 },
    ],
    proposal: 'Global Foyer’s flagship microbrewery experience. Fresh German wheat beer on tap, energetic DJ acoustics, and multi-cuisine corporate gala menus.',
    submittedAt: '2026-08-11T18:00:00Z',
    status: 'pending',
    rating: 4.4,
    user_ratings_total: 3890,
    locality: 'Global Foyer Mall, Golf Course Road',
    timings: '1:00 PM - 2:00 AM',
    amenities: ['In-House Microbrewery', 'Virtual Gaming', 'DJ Dance Floor', 'VIP Bottle Lounge'],
  },
  {
    id: 'bid_nexus_food_toybox',
    rfpId: 'rfp_nexus_food',
    vendorId: 'vp_venue_toybox',
    vendorUserId: 'user_venue_toybox',
    vendorName: 'ToyBox Corporate Events',
    vendorCompany: 'ToyBox Nightclub (Sector 29)',
    category: 'food',
    totalPrice: 660000,
    distanceKm: 2.6,
    matchPercentage: 94,
    lineItems: [
      { description: 'Full Club Buyout or Private Mezzanine Catering (250 pax)', amount: 420000 },
      { description: 'International EDM DJ, Laser & Sound Console, Unlimited Cocktails', amount: 150000 },
      { description: 'Live Finger Food Pass-Arounds & Midnight Slider Buffet', amount: 90000 },
    ],
    proposal: 'High-energy nightlife corporate bash in Sector 29 with world-class audio-visual setup, laser lights, and dedicated bottle service for tech leadership.',
    submittedAt: '2026-08-11T19:30:00Z',
    status: 'pending',
    rating: 4.3,
    user_ratings_total: 1420,
    locality: 'SCO 21-22, Sector 29 Main Market',
    timings: 'Open 24 Hours',
    amenities: ['VIP Bottle Service', 'Laser & Sound Console', 'EDM DJ', 'Private Mezzanine'],
  },
  {
    id: 'bid_nexus_food_02',
    rfpId: 'rfp_nexus_food',
    vendorId: 'vendor_food_02',
    vendorUserId: 'user_vendor_food_02',
    vendorName: 'Amit Soni',
    vendorCompany: 'CyberHub Gourmet Hospitality',
    category: 'food',
    totalPrice: 720000,
    distanceKm: 1.1,
    matchPercentage: 98,
    lineItems: [
      { description: 'Executive Multi-Cuisine Dinner Buffet & Live Counters', amount: 450000 },
      { description: 'Cocktail Bar Setup & Imported Glassware (250 pax)', amount: 150000 },
      { description: 'On-Site Banquet Manager & Full Service Crew', amount: 120000 },
    ],
    proposal: 'Located right inside DLF Cyber Hub — zero logistics delay. Complete 5-star culinary brigade with a complimentary pre-event tasting session.',
    submittedAt: '2026-08-11T18:40:00Z',
    status: 'pending',
    rating: 4.8,
    user_ratings_total: 165,
    locality: 'DLF Cyber Hub Promenade',
    timings: '11:00 AM - 11:30 PM',
    amenities: ['Cyber Hub Location', 'Live Teppanyaki', 'Zero Logistics Delay'],
  },

  // Bids for rfp_indigo_food (Indigo Monthly Lunch)
  {
    id: 'bid_indigo_food_01',
    rfpId: 'rfp_indigo_food',
    vendorId: 'vendor_food_01',
    vendorUserId: 'user_vendor_food',
    vendorName: 'Rajat Verma',
    vendorCompany: 'Royal Feast Catering & Mixology',
    category: 'food',
    totalPrice: 88000,
    distanceKm: 2.8,
    matchPercentage: 93,
    lineItems: [
      { description: 'North Indian Buffet & Live Rajasthani Thali Counter — 80 pax', amount: 56000 },
      { description: 'Live Dosa Corner & South Indian Breakfast Bar', amount: 18000 },
      { description: 'Mocktails, Juices & Cold Brew Station', amount: 14000 },
    ],
    proposal: 'Complete monthly lunch setup with dedicated Jain options. We can execute recurring monthly orders with consistent quality and dedicated account manager.',
    submittedAt: '2026-08-12T10:00:00Z',
    status: 'pending',
  },
  {
    id: 'bid_indigo_food_02',
    rfpId: 'rfp_indigo_food',
    vendorId: 'vendor_food_02',
    vendorUserId: 'user_vendor_food_02',
    vendorName: 'Amit Soni',
    vendorCompany: 'CyberHub Gourmet Hospitality',
    category: 'food',
    totalPrice: 92000,
    distanceKm: 1.1,
    matchPercentage: 90,
    lineItems: [
      { description: 'Regional Indian Lunch Buffet (Jain Certified) — 80 pax', amount: 62000 },
      { description: 'Live Thandai & Fresh Juice Mocktail Bar', amount: 16000 },
      { description: 'Setup, Biodegradable Cutlery & Service Staff', amount: 14000 },
    ],
    proposal: 'Proximity advantage with same-day setup. Full Jain certification for all items. We offer recurring monthly contracts at 8% discount.',
    submittedAt: '2026-08-12T12:00:00Z',
    status: 'pending',
  },

  // ═══ SPORTS BIDS ═══

  // Bids for rfp_nexus_sports (Nexus Cricket League)
  {
    id: 'bid_nexus_sports_01',
    rfpId: 'rfp_nexus_sports',
    vendorId: 'vendor_sports_01',
    vendorUserId: 'user_vendor_sports',
    vendorName: 'Vikram Singh',
    vendorCompany: 'Arena Turf Sports Management',
    category: 'sports',
    totalPrice: 285000,
    distanceKm: 4.5,
    matchPercentage: 95,
    lineItems: [
      { description: 'Full Weekend AstroTurf Venue (Sector 54) — 2 days', amount: 140000 },
      { description: 'Tournament Management, Umpires, Digital Scoring & Trophies', amount: 85000 },
      { description: 'Custom Dri-Fit Jerseys (120 units) & Hydration Lounge', amount: 60000 },
    ],
    proposal: 'Premier sports management agency in Gurgaon. Certified referees, live app-based scoring, custom team kits, drone coverage, and on-site paramedic support.',
    submittedAt: '2026-08-13T10:45:00Z',
    status: 'pending',
    rating: 4.8,
    user_ratings_total: 142,
    locality: 'Sector 54, Golf Course Road',
    timings: '6:00 AM - 11:00 PM',
    amenities: ['AstroTurf Pitch', 'Floodlights', 'Digital Scoring', 'Paramedic on Site'],
  },
  {
    id: 'bid_nexus_sports_playall',
    rfpId: 'rfp_nexus_sports',
    vendorId: 'vp_venue_playall',
    vendorUserId: 'user_venue_playall',
    vendorName: 'PlayAll Tournament Operations',
    vendorCompany: 'PlayAll Sports Complex (Sector 62)',
    category: 'sports',
    totalPrice: 260000,
    distanceKm: 4.2,
    matchPercentage: 99,
    lineItems: [
      { description: 'Dual Multi-Sport AstroTurfs (2 full days) & Dugouts', amount: 130000 },
      { description: 'Certified Umpires, Live Scoring App, Trophies & Man of Match Awards', amount: 75000 },
      { description: 'Custom Sublimation Team Jerseys (120 units) & Hydration Bar', amount: 55000 },
    ],
    proposal: 'Flagship sports complex in Sector 62. Professional floodlights, dedicated player dugouts, live scoreboards, certified umpires, and covered spectator seating for 200+ employees.',
    submittedAt: '2026-08-13T11:30:00Z',
    status: 'pending',
    rating: 4.6,
    user_ratings_total: 1840,
    locality: 'Sector 62, Golf Course Extension Road',
    timings: '6:00 AM - 12:00 AM',
    amenities: ['FIFA Grade Turf', 'Box Cricket', 'Floodlights', 'Live Scoring App', 'Hydration Lounge'],
  },
  {
    id: 'bid_nexus_sports_theballpark',
    rfpId: 'rfp_nexus_sports',
    vendorId: 'vp_venue_theballpark',
    vendorUserId: 'user_venue_theballpark',
    vendorName: 'The BallPark Events Desk',
    vendorCompany: 'The BallPark (Sector 59)',
    category: 'sports',
    totalPrice: 275000,
    distanceKm: 4.9,
    matchPercentage: 96,
    lineItems: [
      { description: 'Full Outdoor Arena & Box Cricket Stadium (2 days)', amount: 140000 },
      { description: 'Baseball Cages Access, Umpires, DJ & Commentary Setup', amount: 80000 },
      { description: 'Dri-Fit Kits, Electrolytes & On-Site Physiotherapist', amount: 55000 },
    ],
    proposal: 'Unique sports arena with box cricket pitches and baseball batting cages. Great open-air lounge, cafe snacks, and live DJ commentary for high-energy corporate leagues.',
    submittedAt: '2026-08-13T12:45:00Z',
    status: 'pending',
    rating: 4.6,
    user_ratings_total: 1350,
    locality: 'Sector 59, Near Ireo Grand Arch',
    timings: '6:00 AM - 10:00 PM',
    amenities: ['Pro Baseball Nets', 'Box Cricket', 'Cafe & Grill', 'Open Air Seating'],
  },
  {
    id: 'bid_nexus_sports_taudevilal',
    rfpId: 'rfp_nexus_sports',
    vendorId: 'vp_venue_taudevilal',
    vendorUserId: 'user_venue_taudevilal',
    vendorName: 'Tau Devi Lal Sports Directorate',
    vendorCompany: 'Tau Devi Lal Sports Complex (Sector 38)',
    category: 'sports',
    totalPrice: 240000,
    distanceKm: 4.8,
    matchPercentage: 94,
    lineItems: [
      { description: 'Stadium Pitch & Grandstand Seating Booking (2 full days)', amount: 120000 },
      { description: 'State Level Umpires, Sound System & Tournament Management', amount: 70000 },
      { description: 'Custom Team Kits, First Aid Station & Medals', amount: 50000 },
    ],
    proposal: 'Gurgaon’s iconic sports stadium. Grandstand seating for up to 1,000 corporate spectators, full pitch boundaries, and official athletic grounds.',
    submittedAt: '2026-08-13T13:30:00Z',
    status: 'pending',
    rating: 4.3,
    user_ratings_total: 3450,
    locality: 'Sector 38, Near Medanta Hospital',
    timings: 'Split Shifts (5:30 AM - 10:00 AM, 4:00 PM - 9:00 PM)',
    amenities: ['Full Sized Stadium', 'Grandstand Seating', 'Olympic Pool', 'VIP Dais'],
  },
  {
    id: 'bid_nexus_sports_02',
    rfpId: 'rfp_nexus_sports',
    vendorId: 'vendor_sports_02',
    vendorUserId: 'user_vendor_sports_02',
    vendorName: 'Manish Rawat',
    vendorCompany: 'ProLeagues Corporate Tournaments',
    category: 'sports',
    totalPrice: 270000,
    distanceKm: 3.2,
    matchPercentage: 97,
    lineItems: [
      { description: 'Floodlit Turf Stadium (Sector 29 Leisure Valley) — 2 days', amount: 130000 },
      { description: 'BCCI Umpires, DJ, Live Commentary & Medals', amount: 80000 },
      { description: 'Breathable Player Kits, Energy Drinks & Physiotherapist', amount: 60000 },
    ],
    proposal: 'Turnkey tournament management with live YouTube broadcast, multi-camera setup, and full logistics in Gurgaon. Guaranteed crowd experience for players and spectators.',
    submittedAt: '2026-08-13T14:10:00Z',
    status: 'pending',
    rating: 4.7,
    user_ratings_total: 98,
    locality: 'Sector 29, Leisure Valley Park',
    timings: '6:00 AM - 11:00 PM',
    amenities: ['Floodlit Stadium', 'Live Broadcast', 'Physiotherapist on Site'],
  },

  // Bids for rfp_indigo_sports (Indigo Badminton Day)
  {
    id: 'bid_indigo_sports_01',
    rfpId: 'rfp_indigo_sports',
    vendorId: 'vendor_sports_01',
    vendorUserId: 'user_vendor_sports',
    vendorName: 'Vikram Singh',
    vendorCompany: 'Arena Turf Sports Management',
    category: 'sports',
    totalPrice: 82000,
    distanceKm: 4.5,
    matchPercentage: 88,
    lineItems: [
      { description: 'Badminton Court (4 courts, 8 hrs) & TT Table Rental (4 tables)', amount: 42000 },
      { description: 'Professional Referees (2 badminton + 1 TT), Rackets & Shuttles', amount: 24000 },
      { description: 'Medals, Certificates & Healthy Snack Station', amount: 16000 },
    ],
    proposal: 'Full sports day management. We handle court setup, bracket management, live scoring board, and award ceremony. Experience with 20+ corporate sports days.',
    submittedAt: '2026-08-14T11:00:00Z',
    status: 'pending',
  },
  {
    id: 'bid_indigo_sports_02',
    rfpId: 'rfp_indigo_sports',
    vendorId: 'vendor_sports_02',
    vendorUserId: 'user_vendor_sports_02',
    vendorName: 'Manish Rawat',
    vendorCompany: 'ProLeagues Corporate Tournaments',
    category: 'sports',
    totalPrice: 78000,
    distanceKm: 3.2,
    matchPercentage: 92,
    lineItems: [
      { description: 'Indoor Sports Facility (Badminton + TT courts, full day)', amount: 40000 },
      { description: 'Certified Referees, Sports Equipment & Digital Bracket App', amount: 22000 },
      { description: 'Gold/Silver/Bronze Medals, Participation Certificates & Photo Booth', amount: 16000 },
    ],
    proposal: 'Clean indoor facility with AC badminton courts. Digital bracket app for live updates. Includes photography and a highlight reel sent to HR post-event.',
    submittedAt: '2026-08-14T14:00:00Z',
    status: 'pending',
  },

  // ═══ TRIPS BIDS ═══

  // Bids for rfp_nexus_trips (Nexus Leadership Offsite)
  {
    id: 'bid_nexus_trips_01',
    rfpId: 'rfp_nexus_trips',
    vendorId: 'vendor_trips_01',
    vendorUserId: 'user_vendor_trips',
    vendorName: 'Priya Nambiar',
    vendorCompany: 'Summit Corporate Retreats',
    category: 'trips',
    totalPrice: 1320000,
    distanceKm: 6.2,
    matchPercentage: 94,
    lineItems: [
      { description: 'Ananda Spa Resort, Rishikesh — 3N/4D (80 pax, twin sharing)', amount: 960000 },
      { description: 'Chartered Volvo AC Coaches (Delhi ↔ Rishikesh) + Airport Transfers', amount: 180000 },
      { description: 'River Rafting, Zip-line, Night Trek & Gala Bonfire Dinner', amount: 180000 },
    ],
    proposal: 'Premium leadership offsite execution with 5-star resort block booking, adventure activity bundle, AV-equipped conference hall, and dedicated retreat coordinator.',
    submittedAt: '2026-08-15T09:00:00Z',
    status: 'pending',
  },
  {
    id: 'bid_nexus_trips_02',
    rfpId: 'rfp_nexus_trips',
    vendorId: 'vendor_trips_02',
    vendorUserId: 'user_vendor_trips_02',
    vendorName: 'Arjun Bose',
    vendorCompany: 'WanderCraft Experiential Travel',
    category: 'trips',
    totalPrice: 1380000,
    distanceKm: 28.0,
    matchPercentage: 91,
    lineItems: [
      { description: 'Kasauli Regency Resort — 3N/4D (80 pax, luxury twin rooms)', amount: 1020000 },
      { description: 'Tempo Travellers & Private Cab Fleet (full itinerary)', amount: 200000 },
      { description: 'Team Building (Bouldering, Archery, Bonfire) & Farewell Dinner', amount: 160000 },
    ],
    proposal: 'Kasauli is ideal for Q4 with stunning weather. Our resort block includes a private conference wing, bonfire pits, adventure trail, and curated Himachali cuisine gala.',
    submittedAt: '2026-08-15T13:00:00Z',
    status: 'pending',
  },

  // Bids for rfp_indigo_trips (Indigo Goa Offsite)
  {
    id: 'bid_indigo_trips_01',
    rfpId: 'rfp_indigo_trips',
    vendorId: 'vendor_trips_01',
    vendorUserId: 'user_vendor_trips',
    vendorName: 'Priya Nambiar',
    vendorCompany: 'Summit Corporate Retreats',
    category: 'trips',
    totalPrice: 940000,
    distanceKm: 6.2,
    matchPercentage: 96,
    lineItems: [
      { description: 'Park Hyatt Goa — 3N/4D (45 pax, deluxe rooms)', amount: 630000 },
      { description: 'IndiGo Economy Flights (DEL-GOI-DEL) + Airport Transfers', amount: 180000 },
      { description: 'Water Sports (Jet Ski, Parasailing), Sightseeing & Beach Bonfire', amount: 130000 },
    ],
    proposal: 'Goa specialization with 30+ corporate groups annually. Block booking advantage at Park Hyatt, curated water sports, and half-day Heritage Goa tour included.',
    submittedAt: '2026-08-16T10:00:00Z',
    status: 'pending',
  },
  {
    id: 'bid_indigo_trips_02',
    rfpId: 'rfp_indigo_trips',
    vendorId: 'vendor_trips_02',
    vendorUserId: 'user_vendor_trips_02',
    vendorName: 'Arjun Bose',
    vendorCompany: 'WanderCraft Experiential Travel',
    category: 'trips',
    totalPrice: 965000,
    distanceKm: 28.0,
    matchPercentage: 89,
    lineItems: [
      { description: 'Novotel Goa Dona Sylvia Resort — 3N/4D (45 pax, beachfront)', amount: 660000 },
      { description: 'SpiceJet Economy Flights + Private Coach Transfers (all days)', amount: 175000 },
      { description: 'Full-Day Water Park, Beach Olympics & Sunset Cruise Dinner', amount: 130000 },
    ],
    proposal: 'Beachfront property for better team bonding. Our curated Goa program includes sunrise yoga, beach Olympics, casino night, and a chartered sunset cruise dinner.',
    submittedAt: '2026-08-16T14:00:00Z',
    status: 'pending',
  },

  // ═══ GIFTS BIDS ═══

  // Bids for rfp_apex_gifts (Apex Diwali Hampers)
  {
    id: 'bid_apex_gifts_01',
    rfpId: 'rfp_apex_gifts',
    vendorId: 'vendor_gifts_01',
    vendorUserId: 'user_vendor_gifts',
    vendorName: 'Ananya Roy',
    vendorCompany: 'Luxe Hampers & Bespoke Awards',
    category: 'gifts',
    totalPrice: 510000,
    distanceKm: 3.1,
    matchPercentage: 97,
    lineItems: [
      { description: 'Premium Dry Fruit & Artisan Mithai Hampers (300 units)', amount: 270000 },
      { description: 'Branded Leather Diary & Pen Set with Logo Embossing', amount: 150000 },
      { description: 'Custom Gift Box, Tissue Wrap & Delivery to Office', amount: 90000 },
    ],
    proposal: 'We have supplied Diwali hampers to 80+ corporates including JP Morgan and McKinsey. Full GST invoice, company logo embossing within 2 working days, and delivery guarantee.',
    submittedAt: '2026-08-16T09:00:00Z',
    status: 'pending',
  },
  {
    id: 'bid_apex_gifts_02',
    rfpId: 'rfp_apex_gifts',
    vendorId: 'vendor_gifts_02',
    vendorUserId: 'user_vendor_gifts_02',
    vendorName: 'Kanchan Mehta',
    vendorCompany: 'Arcade Awards & Gifting Studio',
    category: 'gifts',
    totalPrice: 495000,
    distanceKm: 4.7,
    matchPercentage: 93,
    lineItems: [
      { description: 'Eco-Friendly Hamper Boxes with Organic Mithai & Dry Fruits (300)', amount: 255000 },
      { description: 'Branded Bamboo Diary + Recycled Metal Pen Set', amount: 150000 },
      { description: 'Sustainable Tote Bags & Custom Ribbon Packaging', amount: 90000 },
    ],
    proposal: 'Eco-conscious alternative with plastic-free packaging — great for ESG reporting. 100% compostable boxes, fully customizable with your Apex Financial brand colors.',
    submittedAt: '2026-08-16T13:00:00Z',
    status: 'pending',
  },

  // Bids for rfp_indigo_gifts (Indigo Welcome Kits)
  {
    id: 'bid_indigo_gifts_01',
    rfpId: 'rfp_indigo_gifts',
    vendorId: 'vendor_gifts_01',
    vendorUserId: 'user_vendor_gifts',
    vendorName: 'Ananya Roy',
    vendorCompany: 'Luxe Hampers & Bespoke Awards',
    category: 'gifts',
    totalPrice: 70000,
    distanceKm: 3.1,
    matchPercentage: 95,
    lineItems: [
      { description: 'Premium Laptop Sleeve (Indigo-branded) + Branded Notebook & Pen', amount: 38000 },
      { description: 'Company Hoodie (XS–3XL mix, embroidered logo)', amount: 18000 },
      { description: 'Succulent Plant Kit, Welcome Card & Custom Branded Box', amount: 14000 },
    ],
    proposal: 'Monthly subscription model available at ₹2,200/kit. We stock all components, assemble and deliver to your office by 1st of each month. Minimum order 20 units.',
    submittedAt: '2026-08-13T10:00:00Z',
    status: 'pending',
  },
  {
    id: 'bid_indigo_gifts_02',
    rfpId: 'rfp_indigo_gifts',
    vendorId: 'vendor_gifts_02',
    vendorUserId: 'user_vendor_gifts_02',
    vendorName: 'Kanchan Mehta',
    vendorCompany: 'Arcade Awards & Gifting Studio',
    category: 'gifts',
    totalPrice: 68000,
    distanceKm: 4.7,
    matchPercentage: 91,
    lineItems: [
      { description: 'Laptop Sleeve & Branded Notebook (Vegan Leather Cover)', amount: 36000 },
      { description: 'Premium Hoodie with Chest Embroidery (all sizes)', amount: 18000 },
      { description: 'Air Purifier Plant + Handwritten Welcome Note in Gift Box', amount: 14000 },
    ],
    proposal: 'Unique differentiation: real air-purifier plants instead of succulents — great for employer branding. Branded packaging with tissue paper and ribbon. Monthly recurring fulfilled.',
    submittedAt: '2026-08-13T14:00:00Z',
    status: 'pending',
  },

  // ═══ DRESS & MERCHANDISE BIDS ═══

  // Bids for rfp_apex_dress (Apex Year-End Merchandise)
  {
    id: 'bid_apex_dress_01',
    rfpId: 'rfp_apex_dress',
    vendorId: 'vendor_dress_01',
    vendorUserId: 'user_vendor_dress',
    vendorName: 'Karan Kapoor',
    vendorCompany: 'Threads & Co. Corporate Apparel',
    category: 'dress',
    totalPrice: 565000,
    distanceKm: 8.5,
    matchPercentage: 94,
    lineItems: [
      { description: 'Premium Polo T-Shirts (240 GSM, logo embroidery) — 250 units', amount: 200000 },
      { description: 'Tech Fleece Hoodies with Chest & Back Print — 250 units', amount: 250000 },
      { description: 'Branded Backpacks (water-resistant, embossed logo) — 250 units', amount: 115000 },
    ],
    proposal: 'All items delivered in individual packaging boxes per employee. Production time: 12 working days. Complimentary design consultation & 2 physical samples before final order.',
    submittedAt: '2026-08-17T09:00:00Z',
    status: 'pending',
  },
  {
    id: 'bid_apex_dress_02',
    rfpId: 'rfp_apex_dress',
    vendorId: 'vendor_dress_02',
    vendorUserId: 'user_vendor_dress_02',
    vendorName: 'Sonal Jain',
    vendorCompany: 'BrandWear Merchandise Studio',
    category: 'dress',
    totalPrice: 548000,
    distanceKm: 11.2,
    matchPercentage: 90,
    lineItems: [
      { description: 'Supima Cotton Polo Shirts (220 GSM, embroidered) — 250 units', amount: 188000 },
      { description: 'Premium Fleece Hoodies (all sizes, logo on chest & sleeve) — 250 units', amount: 240000 },
      { description: 'Padded Laptop Backpacks with USB Charging Port — 250 units', amount: 120000 },
    ],
    proposal: 'High-volume specialist. USB-port backpacks are our bestseller for tech corporates. Free name printing on all polo shirts. 10-day production TAT guaranteed.',
    submittedAt: '2026-08-17T13:00:00Z',
    status: 'pending',
  },

  // Bids for rfp_indigo_dress (Indigo Engineers Day T-Shirts)
  {
    id: 'bid_indigo_dress_01',
    rfpId: 'rfp_indigo_dress',
    vendorId: 'vendor_dress_01',
    vendorUserId: 'user_vendor_dress',
    vendorName: 'Karan Kapoor',
    vendorCompany: 'Threads & Co. Corporate Apparel',
    category: 'dress',
    totalPrice: 68000,
    distanceKm: 8.5,
    matchPercentage: 92,
    lineItems: [
      { description: 'Supima Cotton Round-Neck T-Shirts (custom tech graphic) — 90 units', amount: 52000 },
      { description: 'Custom Snapback Caps (90 units, embroidered logo)', amount: 16000 },
    ],
    proposal: 'Engineers Day specialist — we have done this for Razorpay, Amazon, and Cult.fit. Our in-house graphic team will create 3 design options for you to choose. 7-day production.',
    submittedAt: '2026-08-15T11:00:00Z',
    status: 'pending',
  },
  {
    id: 'bid_indigo_dress_02',
    rfpId: 'rfp_indigo_dress',
    vendorId: 'vendor_dress_02',
    vendorUserId: 'user_vendor_dress_02',
    vendorName: 'Sonal Jain',
    vendorCompany: 'BrandWear Merchandise Studio',
    category: 'dress',
    totalPrice: 65000,
    distanceKm: 11.2,
    matchPercentage: 88,
    lineItems: [
      { description: 'Premium Round-Neck T-Shirts (all-over sublimation print) — 90 units', amount: 50000 },
      { description: 'Dad Hats with Embroidered Company Code Motif — 90 units', amount: 15000 },
    ],
    proposal: 'All-over sublimation print gives maximum visual impact for Engineers Day. Vibrant color output, washable up to 60 washes. Same-day size exchange after delivery.',
    submittedAt: '2026-08-15T15:00:00Z',
    status: 'pending',
  },
];
